"""Pose search for items affected by cross-room DINOv2 bleed (Phase 2 substrate fix).

Per the 2026-05-14 reviewer directive following the third STOP in
session 5: for items the extended diagnostic flagged as showing
out-of-scope DINOv2 sensitivity (cross-room bleed from LivingRoom
retexturing), generate candidate viewing poses around the item's
centroid, screen each candidate against:

  1. NavMesh navigability — the candidate's viewing position must be
     within tolerance of a reachable point.
  2. DINOv2 stability under RandomizeMaterials — the candidate's DINOv2
     before-vs-after cosine, averaged across multiple
     RandomizeMaterials draws, must be near 1.0 (the item's
     representation is NOT sensitive to LivingRoom retexturing from
     this pose).

Candidates are generated by sweeping the angle θ around the centroid;
the agent position is `centroid - viewing_distance_m * (sin(θ), cos(θ))`
in (X, Z), and the agent's heading is θ (so the agent faces the
centroid). This preserves the geometric "enters → fills → slides out"
pattern of the close-up segment — only the angle of approach changes.

Output: a candidate report at
`results/inner_pam_v0/phase2_pose_search/pose_search_report.{md,json}`
with the ranked candidates per affected item. The reviewer (or this
script's caller) picks the best surviving candidate, then re-runs
session-4 calibration + the preflight against the adjusted geometry.

Usage:
  nohup python3.12 -u scripts/run_phase2_pose_search.py \\
      > logs/phase2_pose_search_$(date +%Y%m%d_%H%M%S).log 2>&1 &
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
import sys
import traceback
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_ROOT = Path("/mnt/c/Users/Jason/Desktop/Eridos/Weft 2")
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import prior  # noqa: E402

_original_prior_load = prior.load_dataset


def _offline_load_dataset(*args: Any, **kwargs: Any) -> Any:
    kwargs.setdefault("offline", True)
    return _original_prior_load(*args, **kwargs)


prior.load_dataset = _offline_load_dataset  # type: ignore[assignment]

import numpy as np  # noqa: E402
import torch  # noqa: E402
from PIL import Image  # noqa: E402

from shared.encoder.dinov2_encoder import load_frozen_dinov2  # noqa: E402
from v0.src.env.material_perturbation_probe import (  # noqa: E402
    check_navmesh_reachable,
    dinov2_encode_batch,
    items_by_id,
    randomize_livingroom,
    teleport_and_capture,
    teleport_only,
)
from shared.substrate.procthor_house import load_house, make_controller  # noqa: E402


_DEFAULT_ROUTE_JSON = Path(
    "/mnt/c/Users/Jason/Desktop/Eridos/Weft/results/stage_0b_furniture/route.json"
)
_DEFAULT_RESULTS_DIR = _ROOT / "results" / "inner_pam_v0" / "phase2_pose_search"
_DEFAULT_DIAG_REPORT = (
    _ROOT / "results" / "inner_pam_v0" / "phase2_extended_diagnostic"
    / "extended_diagnostic_report.json"
)


def _candidate_poses_from_reachable(
    centroid_x: float,
    centroid_z: float,
    viewing_distance_m: float,
    n_candidates: int,
    reachable: List[Dict[str, float]],
    skip_angle: Optional[float] = None,
    skip_window_deg: float = 15.0,
    distance_tolerance_m: float = 0.50,
    angular_tolerance_deg: float = 20.0,
) -> List[Tuple[float, Dict[str, float], float]]:
    """For each of N target angles θ around the centroid, pick the best NavMesh-
    reachable grid point that is approximately at the target distance and angle.

    Returns a list of `(heading_deg, viewing_position, snapped_distance_m)`
    triples — the heading is set so the agent faces the centroid from the
    snapped position; the position is an exact NavMesh-reachable grid point.

    Skips target angles within ±`skip_window_deg` of `skip_angle` (so we don't
    propose the current pose).
    """
    candidates: List[Tuple[float, Dict[str, float], float]] = []
    reachable_xz = np.array([[p["x"], p["z"]] for p in reachable], dtype=np.float64)
    centroid_xz = np.array([centroid_x, centroid_z], dtype=np.float64)
    deltas = reachable_xz - centroid_xz                       # (N, 2)
    distances = np.linalg.norm(deltas, axis=1)                # (N,)
    # Angle FROM centroid TO each reachable point, in AI2-THOR convention
    # (atan2(dx, dz) with x = east, z = north).
    point_angles_deg = (np.degrees(np.arctan2(deltas[:, 0], deltas[:, 1])) + 360.0) % 360.0

    for i in range(n_candidates):
        target_theta_deg = (360.0 * i) / n_candidates
        if skip_angle is not None:
            diff = abs(((target_theta_deg - skip_angle + 180.0) % 360.0) - 180.0)
            if diff < skip_window_deg:
                continue
        # The agent heading we want is target_theta_deg (so the agent faces
        # the centroid). The angle FROM centroid TO the agent's position is
        # (target_theta_deg + 180°) % 360°.
        point_angle_target = (target_theta_deg + 180.0) % 360.0
        angle_diff = np.abs(((point_angles_deg - point_angle_target + 180.0) % 360.0) - 180.0)
        dist_diff = np.abs(distances - viewing_distance_m)
        mask = (
            (angle_diff <= angular_tolerance_deg)
            & (dist_diff <= distance_tolerance_m)
        )
        candidate_idx = np.where(mask)[0]
        if candidate_idx.size == 0:
            continue
        # Among the matching reachable points, pick the one with smallest
        # combined error (angular + distance, equally weighted in normalised units).
        combined_err = (
            angle_diff[candidate_idx] / angular_tolerance_deg
            + dist_diff[candidate_idx] / distance_tolerance_m
        )
        best = candidate_idx[int(np.argmin(combined_err))]
        snapped_pos = reachable[best]
        snapped_distance = float(distances[best])
        # Heading is set so the agent faces the centroid from the snapped position.
        # heading = atan2(centroid.x - pos.x, centroid.z - pos.z).
        heading_deg = float(
            (math.degrees(math.atan2(
                centroid_x - snapped_pos["x"],
                centroid_z - snapped_pos["z"],
            )) + 360.0) % 360.0
        )
        candidates.append((
            heading_deg,
            {"x": float(snapped_pos["x"]), "y": 0.901, "z": float(snapped_pos["z"])},
            snapped_distance,
        ))
    return candidates


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--route_json", type=Path, default=_DEFAULT_ROUTE_JSON)
    parser.add_argument("--results_dir", type=Path, default=_DEFAULT_RESULTS_DIR)
    parser.add_argument("--diag_report", type=Path, default=_DEFAULT_DIAG_REPORT,
                        help="extended diagnostic report.json; affected items "
                             "read from its 'affected_items' field")
    parser.add_argument("--n_candidates", type=int, default=12,
                        help="number of candidate angles per affected item")
    parser.add_argument("--n_random_draws", type=int, default=3,
                        help="RandomizeMaterials draws per candidate for stability")
    parser.add_argument("--width", type=int, default=300)
    parser.add_argument("--height", type=int, default=300)
    parser.add_argument("--items_override", type=str, default=None,
                        help="comma-separated item labels (e.g. 'DiningTable,Sofa') "
                             "to override the diag report's affected_items list")
    args = parser.parse_args()

    os.environ.setdefault("DISPLAY", ":0")
    if not args.route_json.is_file():
        print(f"[pose] FAIL: route file not found: {args.route_json}", file=sys.stderr)
        return 1
    route = json.loads(args.route_json.read_text())
    items_dict = items_by_id(route)
    args.results_dir.mkdir(parents=True, exist_ok=True)
    frames_dir = args.results_dir / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    # Determine which items to search poses for.
    if args.items_override:
        affected_labels = [s.strip() for s in args.items_override.split(",") if s.strip()]
    elif args.diag_report.is_file():
        diag = json.loads(args.diag_report.read_text())
        affected_labels = list(diag.get("affected_items", []))
    else:
        print(f"[pose] FAIL: no diag report at {args.diag_report} and no --items_override",
              file=sys.stderr)
        return 1
    if not affected_labels:
        print(f"[pose] no affected items to search; nothing to do", flush=True)
        # Write an empty report so downstream tooling has something to read.
        (args.results_dir / "pose_search_report.json").write_text(
            json.dumps({"affected_items": [], "candidates": {}}, indent=2)
        )
        return 0
    print(f"[pose] affected items to search: {affected_labels}", flush=True)

    # Map labels back to item_ids.
    by_label = {it["object_type"]: int(it["item_id"]) for it in route["items"]}
    affected_item_ids: List[int] = []
    for label in affected_labels:
        if label not in by_label:
            print(f"[pose] FAIL: unknown item label '{label}' (have: {list(by_label)})",
                  file=sys.stderr)
            return 1
        affected_item_ids.append(by_label[label])

    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[pose] ts={ts} house_seed={route['seed']} "
          f"n_candidates={args.n_candidates} n_random_draws={args.n_random_draws}",
          flush=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        print("[pose] FAIL: CUDA not available", file=sys.stderr)
        return 1

    house = load_house(seed=int(route["seed"]), min_rooms=4)
    controller = make_controller(house, width=args.width, height=args.height)

    report: Dict[str, Any] = {
        "timestamp_utc": ts,
        "house_seed": int(route["seed"]),
        "affected_items": affected_labels,
        "candidates_per_item": int(args.n_candidates),
        "n_random_draws": int(args.n_random_draws),
        "items": {},
    }

    try:
        # Pre-fetch reachable positions once (NavMesh is static within a session).
        event = controller.step(action="GetReachablePositions")
        if not event.metadata.get("lastActionSuccess", False):
            print("[pose] FAIL: GetReachablePositions did not succeed", file=sys.stderr)
            return 2
        reachable: List[Dict[str, float]] = event.metadata.get("actionReturn") or []
        print(f"[pose] NavMesh: {len(reachable)} reachable positions", flush=True)

        def _navmesh_reachable(pos: Dict[str, float], tol: float = 0.30) -> bool:
            target_x, target_z = float(pos["x"]), float(pos["z"])
            for p in reachable:
                if (
                    abs(float(p["x"]) - target_x) < tol
                    and abs(float(p["z"]) - target_z) < tol
                ):
                    return True
            return False

        # Plan: for each affected item, generate N candidates, run cheap
        # screens (NavMesh + teleport ok), capture frames before + after
        # M material draws, then encode all candidate before/after pairs
        # in one DINOv2 batch.

        # Phase A: generate candidates by snapping each desired angle to the
        # closest NavMesh-reachable grid point at approximately the right
        # distance from the centroid, then verify each candidate teleports.
        per_item_screened: Dict[str, List[Dict[str, Any]]] = {}
        for item_id in affected_item_ids:
            label = items_dict[item_id]["object_type"]
            centroid = items_dict[item_id]["object_centroid"]
            vd = float(items_dict[item_id].get("viewing_distance_m", 1.75))
            current_heading = float(items_dict[item_id]["viewing_heading_deg"])
            cands_raw = _candidate_poses_from_reachable(
                centroid["x"], centroid["z"], vd, args.n_candidates,
                reachable=reachable,
                skip_angle=current_heading, skip_window_deg=15.0,
            )
            screened: List[Dict[str, Any]] = []
            seen_positions: set = set()
            for heading_deg, pos, snapped_dist in cands_raw:
                # De-dup: the snap-to-reachable can map multiple target angles
                # to the same grid point if neighbouring angles' best matches
                # converge. Keep only the first occurrence of each grid point.
                key = (round(pos["x"], 3), round(pos["z"], 3))
                if key in seen_positions:
                    continue
                seen_positions.add(key)
                cand = {
                    "candidate_id": f"{label}_h{int(round(heading_deg)):03d}",
                    "heading_deg": float(heading_deg),
                    "viewing_position": pos,
                    "snapped_distance_m": snapped_dist,
                    "teleport_ok": False,
                    "screened_in": False,
                }
                # NavMesh-reachable by construction (chosen from reachable).
                if teleport_only(controller, pos, heading_deg):
                    cand["teleport_ok"] = True
                    cand["screened_in"] = True
                screened.append(cand)
            n_in = sum(1 for c in screened if c["screened_in"])
            print(f"[pose] {label}: {n_in}/{len(screened)} candidates screened in "
                  f"(teleport_ok at NavMesh-snapped poses)", flush=True)
            per_item_screened[label] = screened
            report["items"][label] = {
                "viewing_position_id": int(item_id),
                "current_pose": {
                    "viewing_position": items_dict[item_id]["viewing_position"],
                    "viewing_heading_deg": current_heading,
                },
                "centroid": centroid,
                "viewing_distance_m": vd,
                "candidates": screened,
            }

        # Phase B: for screened-in candidates, capture frames before + after
        # M RandomizeMaterials draws. We do M global RandomizeMaterials passes,
        # capturing all screened-in candidates per pass.
        # Order: capture all "before" first (one tour); then for each material
        # draw, RandomizeMaterials() once and capture all candidates again.
        capture_keys: List[Tuple[str, str, str]] = []  # (item_label, candidate_id, draw_label)
        capture_frames: List[np.ndarray] = []
        print("[pose] capturing 'before' frames for all screened-in candidates",
              flush=True)
        for label, screened in per_item_screened.items():
            for cand in screened:
                if not cand["screened_in"]:
                    continue
                frame = teleport_and_capture(
                    controller, cand["viewing_position"], cand["heading_deg"]
                )
                capture_keys.append((label, cand["candidate_id"], "before"))
                capture_frames.append(frame)
                # Save the before frame for the audit trail.
                Image.fromarray(frame).save(
                    frames_dir / f"{cand['candidate_id']}_before.png"
                )
        for draw_k in range(1, args.n_random_draws + 1):
            print(f"[pose] RandomizeMaterials draw {draw_k}/{args.n_random_draws}",
                  flush=True)
            ok, _ = randomize_livingroom(controller)
            if not ok:
                print(f"[pose] FAIL: RandomizeMaterials returned not-ok on draw {draw_k}",
                      file=sys.stderr)
                return 2
            for label, screened in per_item_screened.items():
                for cand in screened:
                    if not cand["screened_in"]:
                        continue
                    frame = teleport_and_capture(
                        controller, cand["viewing_position"], cand["heading_deg"]
                    )
                    capture_keys.append((label, cand["candidate_id"], f"draw{draw_k}"))
                    capture_frames.append(frame)
                    # Save the first draw's after frame for audit.
                    if draw_k == 1:
                        Image.fromarray(frame).save(
                            frames_dir / f"{cand['candidate_id']}_after_draw1.png"
                        )

    finally:
        try:
            controller.stop()
        except Exception:
            pass

    if not capture_frames:
        print("[pose] no frames captured; nothing screened in", flush=True)
        (args.results_dir / "pose_search_report.json").write_text(
            json.dumps(report, indent=2)
        )
        return 2

    # Phase C: DINOv2 encode + per-candidate cosine analysis.
    print(f"[pose] loading DINOv2-large + encoding {len(capture_frames)} frames",
          flush=True)
    model = load_frozen_dinov2(device)
    embeddings = dinov2_encode_batch(model, capture_frames, device)
    idx_by_key = {key: i for i, key in enumerate(capture_keys)}

    # For each screened-in candidate, compute before-vs-draw_k cosines and stats.
    for label, screened in per_item_screened.items():
        for cand in screened:
            if not cand["screened_in"]:
                continue
            cid = cand["candidate_id"]
            before_emb = embeddings[idx_by_key[(label, cid, "before")]]
            per_draw_cos: List[float] = []
            for k in range(1, args.n_random_draws + 1):
                after_emb = embeddings[idx_by_key[(label, cid, f"draw{k}")]]
                per_draw_cos.append(float(np.dot(before_emb, after_emb)))
            cand["dinov2_per_draw"] = per_draw_cos
            cand["dinov2_mean"] = float(np.mean(per_draw_cos))
            cand["dinov2_std"] = float(np.std(per_draw_cos, ddof=0))
            cand["dinov2_min"] = float(np.min(per_draw_cos))
            cand["dinov2_max"] = float(np.max(per_draw_cos))
            cand["passes_stability_threshold"] = bool(cand["dinov2_mean"] > 0.98)

    # Rank candidates per item by dinov2_mean (highest first).
    for label, screened in per_item_screened.items():
        screened_in = [c for c in screened if c["screened_in"] and "dinov2_mean" in c]
        screened_in.sort(key=lambda c: c["dinov2_mean"], reverse=True)
        report["items"][label]["ranked_candidates"] = screened_in
        if screened_in:
            best = screened_in[0]
            print(f"[pose] {label}: best candidate {best['candidate_id']} "
                  f"dinov2_mean={best['dinov2_mean']:.4f} "
                  f"std={best['dinov2_std']:.4f} "
                  f"pass_threshold={best['passes_stability_threshold']}",
                  flush=True)
        else:
            print(f"[pose] {label}: no candidates with DINOv2 measurements",
                  flush=True)

    (args.results_dir / "pose_search_report.json").write_text(
        json.dumps(report, indent=2)
    )

    md = ["# Phase 2 Pose Search Report",
          "",
          f"Timestamp: {ts}",
          f"House seed: {route['seed']}",
          f"Candidates per item: {args.n_candidates} (sweep angles, skipping current pose ±15°)",
          f"RandomizeMaterials draws per candidate: {args.n_random_draws}",
          ""]
    for label, screened in per_item_screened.items():
        md.append(f"## {label} (vp_id={by_label[label]})")
        md.append("")
        item_block = report["items"][label]
        cp = item_block["current_pose"]
        md.append(f"Current pose: position={cp['viewing_position']}, heading={cp['viewing_heading_deg']:.2f}°")
        md.append("")
        md.append("### Ranked candidates (top 5)")
        md.append("")
        md.append("| candidate | heading | position | DINOv2 mean | std | passes |")
        md.append("|---|---:|---|---:|---:|---|")
        for c in item_block.get("ranked_candidates", [])[:5]:
            md.append(
                f"| {c['candidate_id']} | {c['heading_deg']:.1f}° | "
                f"x={c['viewing_position']['x']:.2f}, z={c['viewing_position']['z']:.2f} | "
                f"{c['dinov2_mean']:.4f} | {c['dinov2_std']:.4f} | "
                f"{'✓' if c['passes_stability_threshold'] else '✗'} |"
            )
        md.append("")
    (args.results_dir / "pose_search_report.md").write_text("\n".join(md))

    print(f"[pose] wrote {args.results_dir / 'pose_search_report.json'}", flush=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except BaseException as e:
        traceback.print_exc()
        print(f"[pose] FATAL: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(3)
